builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64le
      - mips64le
      - s390x
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - softfloat
    ignore:
      - goos: windows
        goarch: arm
    flags:
      - -trimpath
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
    ldflags:
      - '-s -w -X github.com/prometheus/common/version.Version={{.Version}} -X github.com/prometheus/common/version.BuildDate={{.Date}} -X github.com/prometheus/common/version.Branch={{.Branch}} -X github.com/prometheus/common/version.BuildUser=goreleaser'

changelog:
  skip: true

archives:
  - format_overrides:
      - goos: windows
        format: zip

sboms:
  - artifacts: archive
    documents:
      - "${artifact}.spdx.json"

brews:
  - tap:
      owner: nginxinc
      name: homebrew-tap
      token: '{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}'
    folder: Formula
    homepage: https://www.nginx.com/
    description: NGINX Prometheus Exporter for NGINX and NGINX Plus
    license: Apache-2.0
    install: |
      bin.install "nginx-prometheus-exporter"
    commit_author:
      name: nginx-bot
      email: integrations@nginx.com

signs:
  - cmd: cosign
    artifacts: checksum
    output: true
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - "--output-signature=${signature}"
      - "--output-certificate=${certificate}"
      - "${artifact}"
      - "--yes"

announce:
  slack:
    enabled: true
    channel: '#announcements'
    message_template: 'NGINX Prometheus Exporter {{ .Tag }} is out! Check it out: {{ .ReleaseURL }}'

milestones:
  - close: true

snapshot:
  name_template: 'edge'
