before:
  hooks:
    - make clean
    - go mod tidy
    - go mod verify
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - ppc64le
      - mips64le
      - s390x
    goarm:
      - 5
      - 6
      - 7
    gomips:
      - softfloat
    flags:
      - -trimpath
    gcflags:
      - all=-trimpath={{.Env.GOPATH}}
    asmflags:
      - all=-trimpath={{.Env.GOPATH}}
checksum:
  name_template: 'sha256sums.txt'
changelog:
  skip: true
brews:
  - tap:
      owner: nginxinc
      name: homebrew-tap
    folder: Formula
    homepage: https://www.nginx.com/
    description: NGINX Prometheus Exporter for NGINX and NGINX Plus
    license: Apache-2.0
    install: |
      bin.install "nginx-prometheus-exporter"
    commit_author:
      name: nginx-bot
      email: kubernetes@nginx.com
