language: go
sudo: required
services:
- docker
go:
- "1.10"
script:
- echo "Nginx Prometheus Exporter - commit:${TRAVIS_COMMIT}"
- make test
- make container
- make release && echo "Nginx Prometheus exporter binaries built:" && ls -alh build/nginx-prometheus-exporter* && cat build/sha256sums.txt
- make clean
before_install:
- echo "PR Slug:${TRAVIS_PULL_REQUEST_SLUG}"
- if [[ "${TRAVIS_PULL_REQUEST_SLUG}" == "nginxinc/nginx-prometheus-exporter" || "${TRAVIS_PULL_REQUEST}" == "false" ]]; then
  wget https://${fossalocation}/${fossafile} && tar xzf ${fossafile}
  && ./fossa init
  && FOSSA_API_KEY=${fossapush} ./fossa analyze -t nginx-prometheus-exporter -b ${TRAVIS_BRANCH}; fi
