name: Fossa

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENSE"

concurrency:
  group: ${{ github.ref_name }}-fossa
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scan:
    name: Fossa
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Scan
        uses: fossas/fossa-action@f61a4c0c263690f2ddb54b9822a719c25a7b608f # v1.3.1
        with:
          api-key: ${{ secrets.FOSSA_TOKEN }}
