name: Lint

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
    types:
      - opened
      - reopened
      - synchronize

defaults:
  run:
    shell: bash

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:

  lint:
    permissions:
      contents: read  # for actions/checkout to fetch code
      pull-requests: read  # for golangci/golangci-lint-action to fetch pull requests
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Output Variables
        id: vars
        run: echo "::set-output name=go_version::$(grep "go 1." go.mod | cut -d " " -f 2)"
      - name: Setup Golang Environment
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ steps.vars.outputs.go_version }}
      - name: Lint Code
        uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5 # v3.4.0
