name: Release Drafter

on:
  push:
    branches:
      - main

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@6df64e4ba4842c203c604c1f45246c5863410adb # v5.21.1
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
