name: Release Drafter

on:
  push:
    branches:
      - main

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  update_release_draft:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: read
    steps:
      - uses: release-drafter/release-drafter@569eb7ee3a85817ab916c8f8ff03a5bd96c9c83e # v5.23.0
        with:
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
